### ISSUE TITLE
Cloudflare blocking requests

### ISSUE THREAD

**Issue by Niosop** [portto/blocto-unity-sdk#1]
It looks like Cloudflare isn't configured properly and is blocking web requests from Unity to both https://flow-wallet-testnet.blocto.app/authn and https://flow-wallet-testnet.blocto.app/api/flow/authn

Giving 403 errors.  Am able to connect via Postman occasionally before it starts sending me to a Cloudflare security page with the message:

flow-wallet-testnet.blocto.app
Checking if the site connection is secure
Enable JavaScript and cookies to continue
flow-wallet-testnet.blocto.app needs to review the security of your connection before proceeding.
Ray ID: 7551436ccfc1e7d7
Performance & security by [Cloudflare](https://www.cloudflare.com/?utm_source=challenge&utm_campaign=m)

**Comment by jamisliao** [comment]
The settings related to CloudFlare have been adjusted, and there should be no more problems at the moment.
